# Generated by Django 6.0 on 2026-05-01 19:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='director',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='content',
            name='duration_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='rating',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='content_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='duration',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='genres',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='max_rating',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='platform',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'title')},
        ),
    ]
